=== PoPoWanObi/TERA-CLIENT-Languages/DataCenter_Final_GER/AnimSoundData/AnimSoundData.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:dc="https://vezel.dev/novadrop/dc"
            xmlns="https://vezel.dev/novadrop/dc/AnimSoundData"
            targetNamespace="https://vezel.dev/novadrop/dc/AnimSoundData"
            xsi:schemaLocation="https://vezel.dev/novadrop/dc ../DataCenter.xsd"
            elementFormDefault="qualified">
    <xsd:complexType name="AnimSoundData">
        <xsd:sequence>
            <xsd:element name="AnimSound" type="AnimSoundData_AnimSound" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>

        <xsd:attribute name="animSet" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="AnimSoundData_AnimSound">
        <xsd:sequence>
            <xsd:element name="Sound" type="AnimSoundData_AnimSound_Sound" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>

        <xsd:attribute name="animName" type="xsd:string" />
        <xsd:attribute name="id" type="xsd:int" />
    </xsd:complexType>

    <xsd:complexType name="AnimSoundData_AnimSound_Sound">
        <xsd:attribute name="fadeOutTime" type="xsd:float" />
        <xsd:attribute name="radius" type="xsd:float" use="required" />
        <xsd:attribute name="shapeId" type="xsd:int" use="required" />
        <xsd:attribute name="soundcue" type="xsd:string" />
        <xsd:attribute name="soundcueother" type="xsd:string" />
        <xsd:attribute name="time" type="xsd:float" use="required" />
        <xsd:attribute name="type" type="xsd:string" use="required" />
        <xsd:attribute name="volume" type="xsd:float" use="required" />
    </xsd:complexType>

    <xsd:element name="AnimSoundData" type="AnimSoundData" />
</xsd:schema>

=== PoPoWanObi/TERA-CLIENT-Languages/DataCenter_Final_GER/AnimSoundData/AnimSoundData-00311.xml
<AnimSoundData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/AnimSoundData AnimSoundData.xsd" animSet="SlaveManager_ANI.Anim.SlaveManager_Anim" xmlns="https://vezel.dev/novadrop/dc/AnimSoundData">
    <AnimSound animName="atk01">
        <Sound time="0.563554" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="1.9" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0.301831" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="1.227492" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.3" />
        <Sound time="0.877395" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.WeaponCUE.Weapon_BareHand_LCUE" volume="0.7" />
        <Sound time="0.865385" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_SCUE" volume="0.3" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_Atk01" volume="1.5" />
    </AnimSound>
    <AnimSound animName="atk02">
        <Sound time="0.587189" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="2.817657" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.3" />
        <Sound time="1.702423" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.3" />
        <Sound time="1.66451" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.WeaponCUE.Weapon_BareHand_LCUE" volume="0.6" />
        <Sound time="1.7" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.BodyFallCue.BodyFall_Chainmail_LCUE" volume="0.6" />
        <Sound time="1.7" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.ArmorHitCUE.ArmorHit_Chainmail_MCUE" volume="0.6" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_Atk02" volume="1.5" />
    </AnimSound>
    <AnimSound animName="atk03">
        <Sound time="0.634661" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="3.531153" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.7" />
        <Sound time="4.049552" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="2.324239" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="3.93329" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_SCUE" volume="0.25" />
        <Sound time="2.673026" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.TrafficLineCUE.TrafficLine_S_04CUE" volume="0.55" />
        <Sound time="3.531153" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.BodyFallCue.BodyFall_Chainmail_LCUE" volume="0.8" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_Atk03" volume="1.5" />
    </AnimSound>
    <AnimSound animName="atk04">
        <Sound time="1.195912" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.35" />
        <Sound time="2.025741" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0.910507" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="2.451271" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.2" />
        <Sound time="1.524689" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.2" />
        <Sound time="1.077322" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.WeaponCUE.Weapon_BareHand_LCUE" volume="0.6" />
        <Sound time="1.1" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_01.WeaponDrop_Cue.WeaponDrop_ChainDrop" volume="0.2" />
        <Sound time="1.1" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.ArmorHitCUE.ArmorHit_Chainmail_MCUE" volume="0.6" />
        <Sound time="1.1" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.ArmorHitCUE.ArmorHit_Normal_CUE" volume="0.55" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_Atk04" volume="1.5" />
    </AnimSound>
    <AnimSound animName="Command">
        <Sound time="0.436892" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="1.707923" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="0.6" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="0.602988" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.WeaponCUE.Weapon_BareHand_LCUE" volume="0.4" />
        <Sound time="1.036423" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.WeaponCUE.Weapon_BareHand_LCUE" volume="0.4" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_Command" volume="1.5" />
    </AnimSound>
    <AnimSound animName="command01">
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="1.610826" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_Command01" volume="1.5" />
    </AnimSound>
    <AnimSound animName="Death">
        <Sound time="0.193056" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="1.3" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.6" />
        <Sound time="1.45" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.6" />
        <Sound time="5.465295" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.BodyFallCue.BodyFall_Chainmail_LCUE" volume="1.5" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.2" />
        <Sound time="1.521523" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="4.221893" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.25" />
        <Sound time="5.454436" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_SCUE" volume="0.25" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_Death" volume="2" />
        <Sound time="5.465295" type="Normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.8" />
    </AnimSound>
    <AnimSound animName="DownEnd">
        <Sound time="0.75" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="1.7" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.2" />
        <Sound time="1.65" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_DownEnd" volume="2" />
        <Sound time="2.166" type="Normal" radius="0.7" shapeId="0" soundcue="ModuleSound_02.FootSteps_MonsterCue.MonStep_FullPlate_LCUE" volume="0.3" />
    </AnimSound>
    <AnimSound animName="DownLoop">
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="ModuleSound.RustleCue.Rustle_Chainmail_LCUE" volume="0.2" />
        <Sound time="0" type="normal" radius="0.7" shapeId="0" soundcue="Monster_Voice05.SlaveManager_Cue.SlaveManager_DownLoop" volume="1.5" />
    </AnimSound>
    <AnimSound animName="DownStart">
